### ISSUE TITLE
Create a command to generate the Swagger.Json

### ISSUE THREAD

**Issue by DaniloOliveira28** [swagger-api/swagger-node#211]
Hello,

I was wondering if is possible to create a feature to generate and make available the json with swagger specs to be read by the swagger-ui.

I am user of the older swagger-node-express mw and I was using the function below to create my docs. 
swagger.configureSwaggerPaths("", "/api-docs", ""); 

I did not find how to achieve it with these news changes, so if it is not possible, I will let this feature suggestion.

ps.: I don't know if this place is the correct repo or I should move this suggestion to "swagger-express-mw" repo. 

Thanks,
Danilo

**Comment by prabhatjha** [comment]
Once you have started project using "swagger project start", did you try /swagger?

**Comment by behrangsa** [comment]
I was just going to create a similar issue and ask what's the purpose of `docEndpoints` in the config as it doesn't seem to be working:

```yaml
swagger:
  mapErrorsToJson: true
  docEndpoints:
    raw: /swagger
```

When I start up the app with debugging turned on, it prints out these log statements in the console:

```
$ DEBUG=swagger swagger project start
  swagger project.api: {"swaggerFile":"/Users/behrangsa/Projects/foo/api/swagger/swagger.yaml","name":"foo","main":"app.js","host":"localhost:10010","basePath":"/","localUrl":"http://localhost:10010/","port":"10010"} +0ms
Starting: /Users/behrangsa/Projects/foo/app.js...
  project started here: http://localhost:10010/
  project will restart on changes.
  to restart at any time, enter `rs`
  swagger read config file: /Users/behrangsa/Projects/foo/config/default.yaml +0ms
  swagger config from file: {"swagger":{"mapErrorsToJson":true,"docEndpoints":{"raw":"/swagger"}}} +1ms
  swagger loaded env vars: {"corsOptions":{}} +1ms
  swagger resolved config: {"swagger":{"corsOptions":{},"appRoot":"/Users/behrangsa/Projects/foo","mapErrorsToJson":true,"docEndpoints":{"raw":"/swagger"},"validateResponse":true,"controllersDirs":["/Users/behrangsa/Projects/foo/api/controllers"],"mockControllersDirs":["/Users/behrangsa/Projects/foo/api/mocks"],"configDir":"/Users/behrangsa/Projects/foo/config"}} +0ms
  swagger swagger security config: undefined +146ms
  swagger validator config: {"validateResponse":true} +0ms
  swagger swagger.config will be attached to requests +0ms
  swagger express compatibility middleware configured +1ms
  swagger swaggerTools router config: {"useStubs":false,"controllers":["/Users/behrangsa/Projects/foo/api/controllers"]} +0ms
  swagger cors config: {} +1ms
  swagger swagger raw doc path: /swagger +0ms
  swagger swagger doc filter: /^(?!x-.*)/ +0ms
```

So it reads the config, but going to either of `/swagger` or `/swagger.json` it prints out the following error message in the response:

```
Error: Route defined in Swagger specification (undefined) but there is no defined get operation.
   at send405 (/Users/behrangsa/Projects/foo/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/middleware/swagger-router.js:289:13)
   at swaggerRouter (/Users/behrangsa/Projects/foo/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/middleware/swagger-router.js:398:16)
   at Layer.handle [as handle_request] (/Users/behrangsa/Projects/foo/node_modules/express/lib/router/layer.js:82:5)
   at trim_prefix (/Users/behrangsa/Projects/foo/node_modules/express/lib/router/index.js:302:13)
   at /Users/behrangsa/Projects/foo/node_modules/express/lib/router/index.js:270:7
   at Function.proto.process_params (/Users/behrangsa/Projects/foo/node_modules/express/lib/router/index.js:321:12)
   at next (/Users/behrangsa/Projects/foo/node_modules/express/lib/router/index.js:261:10)
   at expressCompatibility (/Users/behrangsa/Projects/foo/node_modules/swagger-express-mw/node_modules/swagger-node-runner/lib/connect_middleware.js:247:3)
   at Layer.handle [as handle_request] (/Users/behrangsa/Projects/foo/node_modules/express/lib/router/layer.js:82:5)
   at trim_prefix (/Users/behrangsa/Projects/foo/node_modules/express/lib/router/index.js:302:13)
```

**Comment by theganyo** [comment]
There is a bug in the interaction between swagger-

**Comment by theganyo** [comment]
Sorry about that. This should now be fixed. Please update or reinstall the deps in your project and try again. Let me know. Thanks!

**Comment by DaniloOliveira28** [comment]
@theganyo  Thanks. It is working now!

**Comment by theganyo** [comment]
Fantastic!
