### ISSUE TITLE
Response validation failed in mock mode

### ISSUE THREAD

**Issue by davidmach14** [swagger-api/swagger-node#224]
I'm trying to run the hello-world example (for Express.js) in mock mode, but when I try GET operation on adress http://127.0.0.1:10010/hello system returns error 500 with this message:

```
Error: Response validation failed: invalid content type (text/plain).  These are valid: application/json
   at Object.validateContentType (C:\Users\Username\Documents\Private\Projekty\swagger\hello-world\node_modules\swagger-express-mw\node_modules\swagger-node-runner\node_modules\swagger-tools\lib\validators.js:188:11)
   at ServerResponse.end (C:\Users\Username\Documents\Private\Projekty\swagger\hello-world\node_modules\swagger-express-mw\node_modules\swagger-node-runner\node_modules\swagger-tools\middleware\swagger-validator.js:168:20)
   at sendResponse (C:\Users\Username\Documents\Private\Projekty\swagger\hello-world\node_modules\swagger-express-mw\node_modules\swagger-node-runner\node_modules\swagger-tools\middleware\swagger-router.js:221:18)
   at mockResponse (C:\Users\Username\Documents\Private\Projekty\swagger\hello-world\node_modules\swagger-express-mw\node_modules\swagger-node-runner\node_modules\swagger-tools\middleware\swagger-router.js:271:14)
   at stubHandler (C:\Users\Username\Documents\Private\Projekty\swagger\hello-world\node_modules\swagger-express-mw\node_modules\swagger-node-runner\node_modules\swagger-tools\middleware\swagger-router.js:283:5)
   at swaggerRouter (C:\Users\Username\Documents\Private\Projekty\swagger\hello-world\node_modules\swagger-express-mw\node_modules\swagger-node-runner\node_modules\swagger-tools\middleware\swagger-router.js:388:20)
   at Layer.handle [as handle_request] (C:\Users\Username\Documents\Private\Projekty\swagger\hello-world\node_modules\express\lib\router\layer.js:82:5)
   at trim_prefix (C:\Users\Username\Documents\Private\Projekty\swagger\hello-world\node_modules\express\lib\router\index.js:302:13)
   at C:\Users\Username\Documents\Private\Projekty\swagger\hello-world\node_modules\express\lib\router\index.js:270:7
   at Function.proto.process_params (C:\Users\Username\Documents\Private\Projekty\swagger\hello-world\node_modules\express\lib\router\index.js:321:12) 
```

When I try same operation on standard mode (swagger project start), server reply correct message "Hello, stranger! How are you?".

Same situation occurs with every method and even when my own swagger API definition is used.

Environment: Windows 7 Pro 64bit, NodeJS v0.12.2, Swagger v0.6.0

**Comment by theganyo** [comment]
Thanks, David. I've verified that there does appear to be an issue in the mocking system in swagger-tools that doesn't set any content type and so defaults to text/plain and have filed an issue here: https://github.com/apigee-127/swagger-tools/issues/234.

Until this has been addressed, you could either add the text/html to your swagger produces section:
```
produces:
  - application/json
  - text/plain
```

Or, you could add a bit of middleware to set the content-type to application/json for all requests.

**Comment by davidmach14** [comment]
Hello Scott! Thank you for your reply and creating an issue in right place. Your workaround helps me to continue work on my new project. I chose Swagger compared to RAML and Apiary because of a good community and big set of tools so I hope it was a good choice.

**Comment by theganyo** [comment]
We'll take care of you. :)
