### ISSUE TITLE
Sails controller called twice

### ISSUE THREAD

**Issue by antunes20** [swagger-api/swagger-node#271]
I'm using swagger with sails and i'm getting this error:

d:\nodejs\NewsAPI\node_modules\sails-mongo\node_modules\mongodb\lib\utils.js:97
    process.nextTick(function() { throw err; });
                                        ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:691:11)
    at ServerResponse.res.setHeader (d:\nodejs\NewsAPI\node_modules\sails\node_modules\express\node_modules\connect\lib\patch.js:133:22)
    at ServerResponse.res.set.res.header (d:\nodejs\NewsAPI\node_modules\sails\node_modules\express\lib\response.js:577:10)
    at ServerResponse.res.json (d:\nodejs\NewsAPI\node_modules\sails\node_modules\express\lib\response.js:221:36)
    at d:\nodejs\NewsAPI\api\controllers\NewsController.js:34:24
    at d:\nodejs\NewsAPI\api\services\NewsService.js:24:18
    at wrapper (d:\nodejs\NewsAPI\node_modules\sails\node_modules\waterline\node_modules\lodash\index.js:3602:19)
    at applyInOriginalCtx (d:\nodejs\NewsAPI\node_modules\sails\node_modules\waterline\lib\waterline\utils\normalize.js:421:80)
    at wrappedCallback (d:\nodejs\NewsAPI\node_modules\sails\node_modules\waterline\lib\waterline\utils\normalize.js:320:18)
    at _normalizeCallback.callback.success (d:\nodejs\NewsAPI\node_modules\sails\node_modules\waterline\node_modules\switchback\lib\normalize.js:33:31)
    at _switch (d:\nodejs\NewsAPI\node_modules\sails\node_modules\waterline\node_modules\switchback\lib\factory.js:48:28)
    at returnResults (d:\nodejs\NewsAPI\node_modules\sails\node_modules\waterline\lib\waterline\query\finders\basic.js:392:9)
    at d:\nodejs\NewsAPI\node_modules\sails\node_modules\waterline\lib\waterline\query\finders\basic.js:272:16
    at d:\nodejs\NewsAPI\node_modules\sails\node_modules\waterline\lib\waterline\query\finders\operations.js:82:7
    at d:\nodejs\NewsAPI\node_modules\sails\node_modules\waterline\node_modules\async\lib\async.js:49:16
    at Object.async.forEachOf.async.eachOf (d:\nodejs\NewsAPI\node_modules\sails\node_modules\waterline\node_modules\async\lib\async.js:227:20)

The controller is very simple:

module.exports = {

    getAllNews: function (req, res) {
        console.log("Hello");
        NewsService.getNewsOfTheDay(function(news){
            /* news =  [{
                url: "http",
                title: "hey",
                description: "test",
                pubDate: "2015-08-06T10:15:14.387Z",
                published: false
            }];*/
            return res.json(news);
        });
    }
}

and the NewsService:

module.exports = {
    createNews: function (news, cb) {
        News.create(news).exec(function (err, news) {
            if (err) cb("error");
            else cb(news);
        });
    },

    getNewsOfTheDay: function (cb) {
        var date = new Date();
        date.setHours(0,0,0,0);
        console.log(date);
       News.find({pubDate: {'>=': date}, sort: 'pubDate DESC'}).exec(function(err, news){
            if (err) cb("error");
            else cb(news);
        });
    }
}

With the console.log() lines I can see the controller is called twice:

Hello
Thu Aug 06 2015 00:00:00 GMT+0100 (Hora de Verão de GMT)
Hello
Thu Aug 06 2015 00:00:00 GMT+0100 (Hora de Verão de GMT)

swagger.yaml file:

swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
host: localhost:10010
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
  - text/plain
paths:
  /news:
    x-swagger-router-controller: NewsController
    get:
      description: Returns all News to the caller
      operationId: getAllNews
      responses:
        "200":
          description: Success
          schema:
            type: array
            items:
              $ref: "#/definitions/News"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

definitions:
  News:
    required:
      - url
      - title
      - description
      - pubDate
      - published
    properties:
      id:
        type: string
      url:
        type: string
      description:
        type: string
      title:
        type: string
      pubDate:
        type: string
        format: date-time
      published:
        type: boolean
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string

Any clue about this? I also tried with very simple functions without callbacks and the problem is the same. I already tried with different browsers.

**Comment by antunes20** [comment]
I think I found the problem. The problem is with swagger-node-runner version 0.4.5 and above. Since 0.4.5 version,  swagger-node-runner is using the latest version of swagger-tools (0.9.0). With wagger-node-runner 0.4.4 ( swagger-tools (0.8.7)) no problem at all.

**Comment by theganyo** [comment]
Swagger-tools recently went through a couple of revisions - one of which was a breaking change that got reverted. Could you reinstall your deps, making sure you have swagger-tools 0.9.2 and see if that solves it?

**Comment by theganyo** [comment]
Hopefully this has been addressed with the rerelease of swagger-tools. Please reopen if not.
