### ISSUE TITLE
Validate error handling 

### ISSUE THREAD

**Issue by kadjei** [swagger-api/swagger-node#301]
I have a basic error handler placed right after registering my app to swaggerExpress as seen below but during a validation fail my error handler never gets called.

```
      swaggerExpress.register(app);
      
      // Error Handler Middleware
      app.use(function(err,req,res,next){
        console.log("Using error handler middleware....")
        res.json(err);
      })
```
i would like to display all the validation error as JSON objects. or intercept all errors and process them using my error handler is this possible?

stack trace
```
Error: Response validation failed: failed schema validation
   at throwErrorWithCode (/Users/kadjei/projects/swagger/api/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/lib/validators.js:121:13)
   at Object.module.exports.validateAgainstSchema (/Users/kadjei/projects/swagger/api/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/lib/validators.js:150:7)
   at /Users/kadjei/projects/swagger/api/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/middleware/swagger-validator.js:141:22
   at /Users/kadjei/projects/swagger/api/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/async/lib/async.js:358:13
   at /Users/kadjei/projects/swagger/api/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/async/lib/async.js:239:13
   at _arrayEach (/Users/kadjei/projects/swagger/api/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/async/lib/async.js:91:13)
   at _each (/Users/kadjei/projects/swagger/api/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/async/lib/async.js:82:13)
   at async.forEachOf.async.eachOf (/Users/kadjei/projects/swagger/api/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/async/lib/async.js:238:9)
   at _asyncMap (/Users/kadjei/projects/swagger/api/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/async/lib/async.js:357:9)
   at Object.map (/Users/kadjei/projects/swagger/api/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/async/lib/async.js:340:20)
   at validateValue (/Users/kadjei/projects/swagger/api/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/middleware/swagger-validator.js:134:11)
   at ServerResponse.res.end (/Users/kadjei/projects/swagger/api/node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/middleware/swagger-validator.js:242:9)
   at /Users/kadjei/projects/swagger/api/app.js:84:13
   at Layer.handle_error (/Users/kadjei/projects/swagger/api/node_modules/express/lib/router/layer.js:71:5)
   at trim_prefix (/Users/kadjei/projects/swagger/api/node_modules/express/lib/router/index.js:310:13)
   at /Users/kadjei/projects/swagger/api/node_modules/express/lib/router/index.js:280:7
```

**Comment by theganyo** [comment]
Hey Kwame! This is absolutely possible. The newest version of the swagger module creates a project that uses an [error handler](https://github.com/theganyo/swagger-node-runner/blob/master/fittings/json_error_handler.js) by default to map errors that occur to JSON automatically. Of course, you may remove the `onError` handler from your pipe definition in the config/default.yaml file if you don't want it there - or you could even add a similar custom one if you'd like.

**Comment by theganyo** [comment]
That said... it looks like I was perhaps so aggressive with catching errors that I'm not allowing connect-based error handles to fire. I'll look into that.

**Comment by kadjei** [comment]
@theganyo thank you for the quick response.
Sounds great i'll look into some specific use cases where these errors occur.

**Comment by kadjei** [comment]
Below are some outputs per "DEBUG=swagger-tools* swagger project start".
That produce a stack trace

1) Unspecified content type PUSH/POST operations
```
Request validation: failed +0ms
swagger-tools:middleware:validator   Reason: Invalid content type (application/octet-stream).  These are valid: application/json, application/x-www-form-urlencoded
```
2) Failed Schema validation
```
Response validation: failed +1ms
swagger-tools:middleware:validator   Reason: Failed schema validation
```

**Comment by theganyo** [comment]
Ok. I've pushed a patch. You'll need to update your dependencies... but since it's a sub-dependency of swagger-express-mw, you might need to actually reinstall that instead of just `npm update`.

**Comment by kadjei** [comment]
after removing  "swagger-express-mw" as a dependency and  npm install "swagger-express-mw" everything working great.
@theganyo  Thank you.

**Comment by theganyo** [comment]
Great! Thanks!

**Comment by kadjei** [comment]
I have an unrelated question about developing for scalability, i don't know if it's worthy of a new issue. After some frustration about using "$ref" to link definitions/parameters and models i discovered that swagger wasn't build with external references as a part of the core principles. Is this an accurate assumption?

**Comment by pourquoi42** [comment]
removing and reading swagger-express-mw does not work for me. My existing swagger-node based app doesnt work at all any more because req.swagger doesnt exist any more.

@kadjei : could you please reopen this issue?

**Comment by theganyo** [comment]
@pourquoi42 Have you added the new fitting as specified in the release notes here? https://github.com/theganyo/swagger-node-runner/releases/tag/v0.6.0
