### ISSUE TITLE
cannot find module swagger_router

### ISSUE THREAD

**Issue by Nullpo** [swagger-api/swagger-node#303]
I run:
```
$ swagger create project myProject
```
and later I run 
```
cd myProject
swagger project start.
```

And the app crashes.... This is the log of the server (is a Windows 8.1, running with git bash):
```
$ swagger project start
Starting: c:\Users\Nullpo\myProject\app.js...
  project started here: http://localhost:10010/
  project will restart on changes.
  to restart at any time, enter `rs`
c:\Users\Nullpo\myProject\node_modules\swagger-connect\no
de_modules\swagger-node-runner\node_modules\bagpipes\lib\fittingTypes\user.js:28

        throw err;
              ^
Error: Cannot find module c:\Users\Nullpo\myProject\api\
fittings\swagger_router'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at createFitting (c:\Users\Nullpo\myProject\node_modu
les\swagger-connect\node_modules\swagger-node-runner\node_modules\bagpipes\lib\f
ittingTypes\user.js:18:20)
    at Bagpipes.newFitting (c:\Users\Nullpo\myProject\nod
e_modules\swagger-connect\node_modules\swagger-node-runner\node_modules\bagpipes
\lib\bagpipes.js:158:17)
    at Bagpipes.createFitting (c:\Users\Nullpo\myProject\
node_modules\swagger-connect\node_modules\swagger-node-runner\node_modules\bagpi
pes\lib\bagpipes.js:147:22)
    at Bagpipes.createPipe (c:\Users\Nullpo\myProject\nod
e_modules\swagger-connect\node_modules\swagger-node-runner\node_modules\bagpipes
\lib\bagpipes.js:111:19)
    at Bagpipes.getPipe (c:\Users\Nullpo\myProject\node_m
odules\swagger-connect\node_modules\swagger-node-runner\node_modules\bagpipes\li
b\bagpipes.js:50:38)
    at c:\Users\Nullpo\myProject\node_modules\swagger-con
nect\node_modules\swagger-node-runner\node_modules\bagpipes\lib\bagpipes.js:34:1
```

I did this using express, connect and restify...

Thank you for creating this tool! :D

**Comment by theganyo** [comment]
Ouch. Not good. I don't have a similar environment set up right now to be able to debug this properly... but maybe you can help me out by running this with full debug on and posting that here? To do that, set the DEBUG environment variable to "*" and run it again. Something like this:

`DEBUG=* swagger project start`

**Comment by Nullpo** [comment]
Thank you for your reply!

I created a new project with "connect" framework. This is the log:


```
Starting: c:\Users\Pablo\tmp\myProject\app.js...
  project started here: http://localhost:10010/
  project will restart on changes.
  to restart at any time, enter `rs`
  swagger project.api: {"swaggerFile":"c:\\Users\\Pablo\\tmp\\myProject\\api\\sw
agger\\swagger.yaml","name":"myProject","main":"app.js","host":"localhost:10010"
,"basePath":"/","localUrl":"http://localhost:10010/","port":"10010"} +0ms
  nodemon bus new listener: reset (0) +228ms
  nodemon bus new listener: reset (0) +3ms
  nodemon bus new listener: quit (0) +15ms
  nodemon bus new listener: quit (0) +1ms
  nodemon bus new listener: restart (0) +1ms
  nodemon bus new listener: restart (0) +0ms
  nodemon bus new listener: reset (2) +10ms
  nodemon bus emit: reset +2ms
  nodemon:watch resetting watchers +0ms
  nodemon reset +2ms
  nodemon bus new listener: start (0) +2ms
  nodemon bus new listener: start (0) +1ms
  nodemon bus new listener: restart (2) +0ms
  nodemon config: dirs +12ms [ 'c:\\Users\\Pablo\\tmp\\myProject' ]
  nodemon spawning +9ms node app.js
  nodemon bus emit: start +4ms
  nodemon bus new listener: exit (0) +2ms
  nodemon bus new listener: exit (0) +0ms
  nodemon start watch on: *.* +1ms
  nodemon start watch on: c:\Users\Pablo\tmp\myProject +1ms
  nodemon ignore dirs regex(/\.git|node_modules|bower_components|\.sass\-cache/)
 +0ms
  nodemon:watch watching dir: c:\Users\Pablo\tmp\myProject\README.md +60ms
  nodemon:watch watching dir: c:\Users\Pablo\tmp\myProject\app.js +1ms
  nodemon:watch watching dir: c:\Users\Pablo\tmp\myProject\package.json +1ms
  nodemon:watch watching dir: c:\Users\Pablo\tmp\myProject\config\README.md +9ms

  nodemon:watch watching dir: c:\Users\Pablo\tmp\myProject\config\default.yaml +
1ms
  nodemon:watch watching dir: c:\Users\Pablo\tmp\myProject\api\controllers\READM
E.md +11ms
  nodemon:watch watching dir: c:\Users\Pablo\tmp\myProject\api\controllers\hello
_world.js +1ms
  nodemon:watch watching dir: c:\Users\Pablo\tmp\myProject\api\helpers\README.md
 +1ms
  nodemon:watch watching dir: c:\Users\Pablo\tmp\myProject\api\mocks\README.md +
1ms
  nodemon:watch watching dir: c:\Users\Pablo\tmp\myProject\api\swagger\swagger.y
aml +1ms
  nodemon:watch watching dir: c:\Users\Pablo\tmp\myProject\test\api\controllers\
README.md +9ms
  nodemon:watch watching dir: c:\Users\Pablo\tmp\myProject\test\api\controllers\
hello_world.js +2ms
  nodemon:watch watching dir: c:\Users\Pablo\tmp\myProject\test\api\helpers\READ
ME.md +1ms
  pipe loaded env vars: {"corsOptions":{}} +0ms
  pipe resolved config: {"swagger":{"corsOptions":{},"appRoot":"c:\\Users\\Pablo
\\tmp\\myProject","fittingsDirs":["api/fittings","node_modules"],"defaultPipe":n
ull,"swaggerControllerPipe":"swagger_controllers","bagpipes":{"_router":{"name":
"swagger_router","mockMode":false,"mockControllersDirs":["api/mocks"],"controlle
rsDirs":["api/controllers"]},"_swagger_validate":{"name":"swagger_validator","va
lidateResponse":true},"swagger_controllers":[{"onError":"json_error_handler"},"c
ors","swagger_security","_swagger_validate","express_compatibility","_router"],"
swagger_raw":{"name":"swagger_raw"}},"validateResponse":true,"controllersDirs":[
"c:\\Users\\Pablo\\tmp\\myProject\\api\\controllers"],"mockControllersDirs":["c:
\\Users\\Pablo\\tmp\\myProject\\api\\mocks"]}} +5ms
  swagger-tools:middleware Initializing middleware +6ms
  swagger-tools:middleware   Identified Swagger version: 2.0 +3ms
  swagger-tools:middleware   Validation: succeeded +40ms
  pipes creating pipes: +27ms { _router:
   { name: 'swagger_router',
     mockMode: false,
     mockControllersDirs: [ 'api/mocks' ],
     controllersDirs: [ 'api/controllers' ] },
  _swagger_validate: { name: 'swagger_validator', validateResponse: true },
  swagger_controllers:
   [ { onError: 'json_error_handler' },
     'cors',
     'swagger_security',
     '_swagger_validate',
     'express_compatibility',
     '_router' ],
  swagger_raw: { name: 'swagger_raw' } }
  pipes loaded fitting type: connect-middleware +15ms
  pipes loaded fitting type: node-machine +4ms
  pipes loaded fitting type: swagger +3ms
  pipes loaded fitting type: system +2ms
  pipes loaded fitting type: user +2ms
  pipes creating pipe _router: {"name":"swagger_router","mockMode":false,"mockCo
ntrollersDirs":["api/mocks"],"controllersDirs":["api/controllers"]} +1ms
  pipes create fitting {"name":"swagger_router","mockMode":false,"mockController
sDirs":["api/mocks"],"controllersDirs":["api/controllers"]} +3ms
c:\Users\Pablo\tmp\myProject\node_modules\swagger-connect\node_modules\swagger-n
ode-runner\node_modules\bagpipes\lib\fittingTypes\user.js:28
        throw err;
              ^
Error: Cannot find module 'c:\Users\Pablo\tmp\myProject\api\fittings\swagger_rou
ter'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at createFitting (c:\Users\Pablo\tmp\myProject\node_modules\swagger-connect\
node_modules\swagger-node-runner\node_modules\bagpipes\lib\fittingTypes\user.js:
18:20)
    at Bagpipes.newFitting (c:\Users\Pablo\tmp\myProject\node_modules\swagger-co
nnect\node_modules\swagger-node-runner\node_modules\bagpipes\lib\bagpipes.js:158
:17)
    at Bagpipes.createFitting (c:\Users\Pablo\tmp\myProject\node_modules\swagger
-connect\node_modules\swagger-node-runner\node_modules\bagpipes\lib\bagpipes.js:
147:22)
    at Bagpipes.createPipe (c:\Users\Pablo\tmp\myProject\node_modules\swagger-co
nnect\node_modules\swagger-node-runner\node_modules\bagpipes\lib\bagpipes.js:111
:19)
    at Bagpipes.getPipe (c:\Users\Pablo\tmp\myProject\node_modules\swagger-conne
ct\node_modules\swagger-node-runner\node_modules\bagpipes\lib\bagpipes.js:50:38)

    at c:\Users\Pablo\tmp\myProject\node_modules\swagger-connect\node_modules\sw
agger-node-runner\node_modules\bagpipes\lib\bagpipes.js:34:10

```

**Comment by Hanspagh** [comment]
+1

**Comment by Hanspagh** [comment]
To my understanding, its a problem with ```   fittingsDirs: [ api/fittings/, node_modules ] ``` in the default config not getting parsed correctly.

**Comment by theganyo** [comment]
I apologize for the delay. I'm working on getting a Windows environment set up so I can debug this.

**Comment by theganyo** [comment]
@Nullpo @Hanspagh Not surprisingly, it was a Windows path issue oversight. It should be fixed now. Please delete your app's node_modules and do a new `npm install`.

**Comment by Nullpo** [comment]
Works without problems. Thank you!!!!! :D

**Comment by satishbhakta** [comment]
I am trying to run this sample, 
https://github.com/apigee-127/swagger-node-examples/tree/master/volos-plugins

but it gives same error as above "Cannot find module 'volos-swagger' "
pls suggest fix/ workaround..

error log is below
****************
Error initializing middleware
Error: Cannot find module 'volos-swagger'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\SDB\Software\apigee127\swagger-node-examples-maste
r\volos-plugins\api\fittings\volos-swagger-oauth\index.js:1:75)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
***************

**Comment by WaldoJeffers** [comment]
Also seeing this issue. I'm using [@std/esm](https://github.com/standard-things/esm). Might be related.

**Comment by ROIZENGH** [comment]
the fix I found was @ node_modules/bagpipes/libfittingTypes/user.js line 24

change: 
`var split = err.message.split(path.sep);`

to:
`var split = err.message.split('\n')[0].split(path.sep);`

**Comment by barrettm51** [comment]
> the fix I found was @ node_modules/bagpipes/libfittingTypes/user.js line 24
> 
> change: `var split = err.message.split(path.sep);`
> 
> to: `var split = err.message.split('\n')[0].split(path.sep);`

Works great! Don't know how you found this but thank you
