### ISSUE TITLE
req.files must be provided for 'formData'

### ISSUE THREAD

**Issue by kadjei** [swagger-api/swagger-node#336]
For testing purposes i specified incorrect post methods (x-www-form-urlencoded, raw, binary) to handle multipart/form-data.
A failed response is expected but an error is thrown rather than being caught by my error handler. 

Spec
```
consumes:
  - application/json 
  - multipart/form-data
  - x-www-form-urlencoded
post:
      operationId: uploadCSV
      description: "Upload comma delimited csv"
      parameters:
        - name: database
          in: query
          type: string
          required: true
        - name: CSVFile
          in: formData
          type: file
          required: true 
      responses:
        200:
          description: "Successfully uploaded csv"
          schema:
              $ref: "#/definitions/successResponse"
        default:
          description: "Error uploading csv"
          schema:
            $ref: "#/definitions/errorResponse"
```

Stack
```
Error: req.files must be provided for 'formData' parameters of type 'file'
2016-01-04T17:57:45.055111+00:00 app[web.1]:     at Parameter.getValue (/app/node_modules/sway/lib/types/parameter.js:143:15)
2016-01-04T17:57:45.055111+00:00 app[web.1]:     at /app/node_modules/swagger-node-runner/fittings/swagger_params_parser.js:40:44
2016-01-04T17:57:45.055109+00:00 app[web.1]:
2016-01-04T17:57:45.055112+00:00 app[web.1]:     at Array.forEach (native)
2016-01-04T17:57:45.055112+00:00 app[web.1]:     at /app/node_modules/swagger-node-runner/fittings/swagger_params_parser.js:39:46
2016-01-04T17:57:45.055114+00:00 app[web.1]:     at finishedParseBody (/app/node_modules/swagger-node-runner/fittings/swagger_params_parser.js:125:12)
2016-01-04T17:57:45.055114+00:00 app[web.1]:     at /app/node_modules/async/lib/async.js:721:13
2016-01-04T17:57:45.055115+00:00 app[web.1]:     at /app/node_modules/async/lib/async.js:52:16
2016-01-04T17:57:45.055116+00:00 app[web.1]:     at /app/node_modules/async/lib/async.js:269:32
2016-01-04T17:57:45.055116+00:00 app[web.1]:     at /app/node_modules/async/lib/async.js:44:16
2016-01-04T17:57:45.055117+00:00 app[web.1]:     at /app/node_modules/async/lib/async.js:718:17
2016-01-04T17:57:45.055118+00:00 app[web.1]:     at /app/node_modules/async/lib/async.js:167:37
2016-01-04T17:57:45.055119+00:00 app[web.1]:     at parseText (/app/node_modules/swagger-node-runner/fittings/swagger_params_parser.js:118:60)
2016-01-04T17:57:45.055119+00:00 app[web.1]:     at /app/node_modules/async/lib/async.js:713:13
2016-01-04T17:57:45.055120+00:00 app[web.1]:     at Immediate.iterate [as _onImmediate] (/app/node_modules/async/lib/async.js:262:13)
2016-01-04T17:57:45.055121+00:00 app[web.1]:     at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by amitonkare** [comment]
hey! Whats the solution on this?

**Comment by ChristianRich** [comment]
You need to use a library like npm multer and add it to your middleware stack. This will catch the file on POST and attach it to the req object as req.files

**Comment by SandyChapman** [comment]
FYI, my solution for this was to use body-parser.

Install using `npm install body-parser --save`.

Then, in your app.js:

```
var bodyParser = require('body-parser');
...
SwaggerExpress.create(config, function(err, swaggerExpress) {
  ...
  app.use(bodyParser());
  ...
  swaggerExpress.register(app);
  ...
}
```

Then instead of using `req.swagger.params.PARAM_NAME.value`, use `req.body.PARAM_NAME.value`.

**Comment by b4dnewz** [comment]
with multer is working good but only for multiple files `multer.fields([{name: 'file'}])` since multer add the **req.files** property but I can't make it working with single file:

`multer.single('file')` will create **req.file** instead of **req.files** and swagger will throw this err:
```
Error: req.files must be provided for 'formData' parameters of type 'file'
    at Parameter.getValue (C:\path\to\api\node_modules\sway\lib\types\parameter.js:141:15)
```

any idea on how to make this work?

**Comment by summit2020** [comment]
I got a work around on it.
Every http middleware stack runs http request to complete request parser which also declare req.file or req.files as array of files for some http frameworks.
Just jump to (C:\path\to\api\node_modules\sway\lib\types\parameter.js:141:15) line number & edit it to req.file where key is file & parameter value will be set to it.
It works for sure, thanks!

**Comment by rahulthakur319** [comment]
@b4dnewz : This custom middleware worked for me to handle single file upload. If `req.file` is there it puts it into `req.files`

```
app.use(function (req, res, next) {
    if(req.file){
      req.files = req.file  
    }
    next();
  });
```

**Comment by b4dnewz** [comment]
@rahulthakur319 nice trick

but I think this issue should be addressed from swagger-node project rather than by users, since multer is the de-facto standard for handling multipart-form-data

it's a pretty simple [change](https://github.com/apigee-127/sway/blob/master/lib/types/parameter.js#L142-L147 ):

```js
if (_.isUndefined(req.files)) { // _.isUndefined(req.files) || _.isUndefined(req.file)

}
```
Also using req.files[0] it's a legit trick
