### ISSUE TITLE
Swagger document validation error is entirely useless and very frustrating

### ISSUE THREAD

**Issue by stevekuznetsov** [swagger-api/swagger-node#354]
Inside of a `parameters` field in a `path`, I had used `id` instead of `name`. `swagger project edit` rendered without errors, albeit with an empty spot for the name of the parameter. Trying to run the app, I got:

```
$ node app.js 
Error in callback! Tossing to global error handler. Error: Swagger validation errors:
    at /tmp/swagger/hello-world/node_modules/swagger-node-runner/index.js:210:23
/tmp/swagger/hello-world/node_modules/swagger-node-runner/index.js:241
      process.nextTick(function() { throw err; });
                                    ^

Error: Swagger validation errors:
    at /tmp/swagger/hello-world/node_modules/swagger-node-runner/index.js:210:23
```

This error message is absolutely useless. The validation errors should show where the file failed validation.

**Comment by pzgz** [comment]
+1 for this issue, I am getting following errors all the time:

```
Error initializing middleware
Error: Swagger document(s) failed validation so the server cannot start
    at /Users/leon/Workspace/laic/renren-help/rrh-api/node_modules/swagger-node-runner/node_modules/swagger-tools/index.js:72:13
    at cbWrapper (/Users/leon/Workspace/laic/renren-help/rrh-api/node_modules/swagger-node-runner/node_modules/swagger-tools/lib/specs.js:1035:5)
```

Anyway to show more detail about swagger validation error?

**Comment by tjaartvdwalt** [comment]
I agree that the validation error messages needs work.

For my I got a long stack trace, that did not give the actual validation error. 

After some debugging I realized it is because my `POST` request is JSON, but this is not allowed by default. I had to add:
```yaml
post:
  consumes:
    - application/json
```
My point being, that a useful validation error stating exactly which validation rule was broken, and on what line it was broken would have saved me a couple of hours.

**Comment by joeSaad** [comment]
@tjaartvdwalt I have done the same by adding consumes: application/json and also added produces: application/json
been getting this error: 
"message": "Response validation failed: invalid content type (text/plain).  These are valid: application/json, application/x-yaml"

No idea, what and how to fix it even after so much research.

**Comment by rmharrison** [comment]
I agree that not having the error propagate up the call stack is frustrating. 

Quick work around: `swagger validate swagger.yaml` will show you most errors. 

Longer work around: SwaggerEditor via `swagger project edit` will give you a line number. 
Unfortunately, it sometimes crashes on larger files. This is a known issue (swagger-api/swagger-editor#448); it's better than it was.

**Comment by stevekuznetsov** [comment]
@rmharrison those workarounds may not *always* work -- in my case the editor just showed a blank field instead of crashing, so it was very hard to tell if something was wrong.
