### ISSUE TITLE
swagger project create fails with  SyntaxError: Invalid regular expression

### ISSUE THREAD

**Issue by edoloughlin** [swagger-api/swagger-node#518]
```
 » swagger project create something                                                                  1 ↵
? Framework? (Use arrow keys)
> connect
  express
  hapi
  restify
  sails SyntaxError: Invalid regular expression: /.{1,0}/: numbers out of order in {} quantifier
    at RegExp (<anonymous>)
    at breakLines (C:\devtools\node-v8.4.0-win-x64\node_modules\swagger\node_modules\inquirer\lib\utils\screen-manager.js:108:15)
    at module.exports.ScreenManager.render (C:\devtools\node-v8.4.0-win-x64\node_modules\swagger\node_modules\inquirer\lib\utils\screen-manager.js:55:22)
    at Prompt.render (C:\devtools\node-v8.4.0-win-x64\node_modules\swagger\node_modules\inquirer\lib\prompts\list.js:103:15)
    at Prompt._run (C:\devtools\node-v8.4.0-win-x64\node_modules\swagger\node_modules\inquirer\lib\prompts\list.js:74:8)
    at Prompt.run (C:\devtools\node-v8.4.0-win-x64\node_modules\swagger\node_modules\inquirer\lib\prompts\base.js:57:8)
    at Object.<anonymous> (C:\devtools\node-v8.4.0-win-x64\node_modules\swagger\node_modules\inquirer\lib\ui\prompt.js:84:12)
    at module.exports (C:\devtools\node-v8.4.0-win-x64\node_modules\swagger\node_modules\run-async\index.js:15:21)
    at AnonymousObservable.__subscribe (C:\devtools\node-v8.4.0-win-x64\node_modules\swagger\node_modules\inquirer\lib\utils\utils.js:16:7)
    at AnonymousObservable.tryCatcher (C:\devtools\node-v8.4.0-win-x64\node_modules\swagger\node_modules\rx-lite\rx.lite.js:63:31)

```

**Comment by edoloughlin** [comment]
Looks the inquirer module doesn't support Cygwin. Works ok in a CMD window.
