### ISSUE TITLE
Jest support

### ISSUE THREAD

**Issue by DanielRamosAcosta** [swagger-api/swagger-node#560]
Has anyone achieved to replace mocha tets with jest? I'm unable to do it.

When it reaches the "SwaggerExpress.create" a HTTP request gets launched to `http://127.0.0.1:80/home/dramos/Documentos/Repos/Mios/swagger-es6-boilerplate/api/swagger/swagger.yaml` and all my tests fails :cry: 

Just for trying, I've open an HTTP server in `/` (so that files gets resolved) and it gives de following error:

```
TypeError: fittingFactory is not a function
        at Bagpipes.newFitting (/home/dramos/Documentos/Repos/Mios/swagger-es6-boilerplate/node_modules/bagpipes/lib/bagpipes.js:158:17)
        at Bagpipes.createFitting (/home/dramos/Documentos/Repos/Mios/swagger-es6-boilerplate/node_modules/bagpipes/lib/bagpipes.js:147:22)
        at Bagpipes.createPipe (/home/dramos/Documentos/Repos/Mios/swagger-es6-boilerplate/node_modules/bagpipes/lib/bagpipes.js:111:19)
        at Bagpipes.getPipe (/home/dramos/Documentos/Repos/Mios/swagger-es6-boilerplate/node_modules/bagpipes/lib/bagpipes.js:50:38)
        at /home/dramos/Documentos/Repos/Mios/swagger-es6-boilerplate/node_modules/bagpipes/lib/bagpipes.js:34:10
        at /home/dramos/Documentos/Repos/Mios/swagger-es6-boilerplate/node_modules/lodash/index.js:3073:15
        at baseForOwn (/home/dramos/Documentos/Repos/Mios/swagger-es6-boilerplate/node_modules/lodash/index.js:2046:14)
        at /home/dramos/Documentos/Repos/Mios/swagger-es6-boilerplate/node_modules/lodash/index.js:3043:18
        at Function.<anonymous> (/home/dramos/Documentos/Repos/Mios/swagger-es6-boilerplate/node_modules/lodash/index.js:3346:13)
        at new Bagpipes (/home/dramos/Documentos/Repos/Mios/swagger-es6-boilerplate/node_modules/bagpipes/lib/bagpipes.js:33:5)
        at Object.createPipes [as create] (/home/dramos/Documentos/Repos/Mios/swagger-es6-boilerplate/node_modules/bagpipes/lib/bagpipes.js:18:12)
        at Object.create (/home/dramos/Documentos/Repos/Mios/swagger-es6-boilerplate/node_modules/bagpipes/lib/index.js:10:19)
        at createPipes (/home/dramos/Documentos/Repos/Mios/swagger-es6-boilerplate/node_modules/swagger-node-runner/index.js:306:19)
        at /home/dramos/Documentos/Repos/Mios/swagger-es6-boilerplate/node_modules/swagger-node-runner/index.js:232:23
        at <anonymous>
        at process._tickDomainCallback (internal/process/next_tick.js:228:7)

```

**Comment by manh-vv** [comment]
Do @DanielRamosAcosta have solution on the issue?
I am facing with the same problem.

**Comment by manh-vv** [comment]
I solve my problem. I use `swagger-express-middleware`. And this [conversation](https://github.com/apigee-127/swagger-tools/issues/495#issuecomment-294563708) show me what problem is.

The swagger need time to configuration. If in your test put head sleep time 2s for example. The test may run normally.

Hope this help others.

**Comment by DanielRamosAcosta** [comment]
I you're starting developing your API, I would recomend you [Nest](https://nestjs.com/). `swagger-node` seems to be very abandoned.

**Comment by samuelmgalan** [comment]
I'm in the same position as @manh-vv but I don't like the idea of putting everything to sleep for n seconds. Any other solution to use Jest with Swagger?

I've tried to separate `app` from `server` but it doesn't work either. I guess because is inside the function `create(config)` where swagger routes are mixed with express. 

What i've seen so far is that the server doesn't need to start in order to test the routes.
Using as an example the Supertest documentation `app.listen(port)` is not needed. But with Swagger it can't be detached.

Also, another issue is the asynchronous function `create(config)`. Because of it when `module.exports = app` is called it is not initialized yet.

All is a mess... And i wonder how swagger does it when `swagger project test` is invoked.

**Comment by DanielRamosAcosta** [comment]
If enyone comes here: swagger-node is not maintained, I think. I'm using NestJS right now.
